function [hfig, X] = pltn_M2data(Z, Znoise, varargin)

% plots eigen-mode amplitudes and residue as a fn. of freq
% Matthew Hole Jan. 2002 
% plot n mode number versus frequency

fs = 14;  % font size
lw = 1.5; % line width
fnorm= 1e+3;

h0=figure;
set(gca,'FontSize', fs, 'LineWidth',lw,'Box','on','TickLength',[0.02 0.02],'TickDir','in'); hold on;

% ===============================================================
h3 = subplot('Position', [0.15 0.12 0.8 0.28]);
set(gca,'FontSize', fs, 'LineWidth',lw,'Box','on','TickLength',[0.02 0.02],'TickDir','in'); hold on;
xlabel('f [Hz]');
ylabel('probability');
hold on;

% define residue tupe
residue.MarkerFaceColor ='k';
residue.MarkerSize      = 1;
residue.Marker          ='none';
residue.LineStyle       = '-';
residue.Color           = 'k';
residue.LineWidth       = 1.5;

amp1.Marker          ='none';
amp1.LineStyle       = '--';
amp1.Color           = 'k';
amp1.LineWidth       = 1.5;

amp2.Marker          ='none';
amp2.LineStyle       = ':';
amp2.Color           = 'k';
amp2.LineWidth       = 1.5;

Nf = length(Z.f);
NM = size(Z.n, 2);

% smooth residue about frequency bins 
X = Z;

if ~isempty(varargin)
    if length(varargin) == 2
        filt = varargin{2};
    end
end

if exist('filt')~=1      
    filt.gaussian = 1;
    filt.arbitrary= 0;
end

if filt.gaussian==1

   if isfield(Z,'dtfil') 
       filt.fsigma = 0.44 / Z.dtfil *2*sqrt(2*log(2));
   else
       filt.fsigma = 1.5*1e+3;
       filt.fsigma = 200;
       filt.fsigma = 100;
       filt.fsigma = 1.25*1e+3;
   end
   filt.df    = Z.f(2)-Z.f(1);
   sigma_n    = filt.fsigma/filt.df;
   Nw         = Nf + (1-mod(Nf,2)); % make Nw odd
   nw         = (Nw-1)/2;
   ic         = nw+1;
   for i=1:Nw
       w(i) = 1/(sqrt(2*pi)*sigma_n)*exp(-(i-ic)^2/(2* sigma_n^2));
   end;

   Zoff.dF(1:Nf)         = 0.0;
   Zoff.a(1:Nf,:)        = 0.0 * Z.a;
   Zoff.dF(Nf+1:2*Nf)    = Z.dF;
   Zoff.a(Nf+1:2*Nf,:)   = Z.a;
   Zoff.dF(2*Nf+1:3*Nf)  = 0.0;
   Zoff.a(2*Nf+1:3*Nf,:) = 0.0 * Z.a;

   for i=1:Nf
       X.dF(i) = Zoff.dF(Nf+i-nw:Nf+i+nw) *w.' ;
       X.a(i,:)= abs(Zoff.a(Nf+i-nw:Nf+i+nw,:)).'*w.' ;
   end;

elseif filt.arbitrary==1
    
   filt.sigma = 0;
   
   w = [0.2 0.4 0.5 1 0.5 0.4 0.2];
   w = w/sum(w)
   nw= (length(w)-1)/2
   
   Zoff.dF(1:Nf)         = 0.0;
   Zoff.a(1:Nf,:)        = 0.0;
   Zoff.dF(Nf+1:2*Nf)    = Z.dF;
   Zoff.a(Nf+1:2*Nf,:)   = Z.a;
   Zoff.dF(2*Nf+1:3*Nf)  = 0.0;
   Zoff.a(2*Nf+1:3*Nf,:) = 0.0;
   
   for i=1+nw:Nf-nw
       X.dF(i) = Zoff.dF(Nf+i-nw:Nf+i+nw) *w.' ;
       X.a(i,:)= abs(Zoff.a(Nf+i-nw:Nf+i+nw,:)).'*w.' ;
   end;
else
    filt.fsigma = 0;
    X = Z;
end;

X.filt = filt;

% w = w/sum(w)
% nw= (length(w)-1)/2
% for i=1+nw:Nf-nw
%    X.dF(i) = Z.dF(i-nw:i+nw).'*w.' ;
%    X.a(i,:)= abs(Z.a(i-nw:i+nw,:)).'*w.' ;
% end;

% map residue to cdf for noise
% extrapolate for 

% -----------------------------------------------------------------
load n2f_gauss.mat pdf2_norm pdf1_norm
pdf1_norm = pdf_poly(pdf1_norm);
pdf2_norm = pdf_poly(pdf2_norm);

Nhr = 1e+4; 
dr  = 1/(Nhr-1);
pdf2_norm.hrbin = 0 : dr : 1;
pdf2_norm.hFr     = interp1(pdf2_norm.rbin, pdf1_norm.Fr, pdf2_norm.hrbin,'spline','extrap');

% interpolate cdf that signal was generated by noise
NM = size(Z.n,2);
X.FdF(1:Nf) = interp1(pdf2_norm.rbin, pdf2_norm.Fr, abs(X.dF(1:Nf)),'spline','extrap');

Nha = 1e+4; 
da  = (max(pdf2_norm.abin) - min(pdf2_norm.abin))/(Nha-1);
pdf2_norm.habin   = min(pdf2_norm.abin) : da : max(pdf2_norm.abin);
pdf2_norm.hFa     = interp1(pdf2_norm.abin, pdf2_norm.Fa, pdf2_norm.habin,'spline');

% interpolate cdf that signal was generated by noise
% load spec_M2.mat x_noise x1_noise x2_noise
% load M=1 noise statistics
load ../Bnoise_rms.mat Bnoise
X.a_rms = interp1(Bnoise.f, Bnoise.a_rms,X.f, 'linear','extrap');

if isempty(varargin)
    snr_confidence = 4;
else
    snr_confidence = varargin{1};
end 

% noise calculation (Guess multiplier?)
X.a_rms       = snr_confidence * Znoise.alpha * X.f.^ Znoise.beta;
X.a_rms       = snr_confidence * Znoise.alpha * X.f.^ Znoise.beta;
% X.a_rms       = 10 * Znoise.alpha * X.f.^ Znoise.beta;
X.Fda(1:Nf,1) = 1 - interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,1))./X.a_rms ,'v5cubic',1e-5);
X.Fda(1:Nf,2) = 1 - interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,2))./X.a_rms ,'v5cubic',1e-5);

tol = 1e-5;
i_erange = find((X.Fda(:,1) < tol)|isnan(X.Fda(:,1)));
X.Fda(i_erange,1) = tol;
i_erange = find((X.Fda(:,2) < tol)|isnan(X.Fda(:,2)));
X.Fda(i_erange,2) = tol;


% shift centre
% ymin = 1e-3;
% ymax = 1.2;
% for i=1:Nf
%     X.Fa(i) = 1 - interp1(pdf1_gauss.abin * X.a_rms(i), pdf1_gauss.Fa, abs(X.a(i)), 'linear',1-ymin/2);
%     if (X.Fa(i)==0) X.Fa(i) = ymin/2; end;
% end

% plot probability that amplitude is noise
% hs2 = plot(X.f/fnorm, X.Fa,'k--','LineWidth',llw)

% X.Fda(1:Nf,1) = 1 - interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,1))./X.a_rms ,'v5cubic');
% X.Fda(1:Nf,2) = 1 - interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,2))./X.a_rms ,'v5cubic');

% X.Fda(1:Nf,1) = interp1(pdf2_norm.habin.*(x_noise(1) * X.f.^ x_noise(2)), pdf2_norm.hFa, abs(X.a(1:Nf,1)) ,'spline','extrap');
% X.Fda(1:Nf,2) = interp1(pdf2_norm.habin.*(x_noise(1) * X.f.^ x_noise(2)), pdf2_norm.hFa, abs(X.a(1:Nf,2)) ,'spline','extrap');
% X.Fda(1:Nf,1) = interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,1))./(x_noise(1) * X.f.^ x_noise(2)) ,'spline','extrap');
% X.Fda(1:Nf,2) = interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,2))./(x_noise(1) * X.f.^ x_noise(2)) ,'spline','extrap');
% X.Fda(1:Nf,2) = interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,2)),'spline','extrap');
% X.Fda(1:Nf,1) = interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,1)));
% X.Fda(1:Nf,2) = interp1(pdf2_norm.habin, pdf2_norm.hFa, abs(X.a(1:Nf,2)));



% plot interpolated cdf
hr  = semilogy(X.f/fnorm, X.FdF,residue); 
ha1 = semilogy(X.f/fnorm, X.Fda(:,1),amp1); 
ha2 = semilogy(X.f/fnorm, X.Fda(:,2),amp2); 
fmin = min(X.f) + 2 * filt.fsigma;
fmax = max(X.f) - 2 * filt.fsigma;
FdFmin = 0.5 * 10^(floor(log10(min(abs(X.FdF))))) %added absolute value;
FdFmax = 2;

% plot 1% confidence line
plot([fmin/fnorm fmax/fnorm], [0.01 0.01],'r');

disp("Axes limits: ")
disp(FdFmin)
disp(FdFmax)
axis([fmin/fnorm fmax/fnorm FdFmin FdFmax]);
axis([fmin/fnorm fmax/fnorm 0.001 FdFmax]);

legend([hr ha1 ha2], {'C_r','1-C_{\beta,1}', '1-C_{\beta,2}'});
% title(['#',num2str(X.shot),'@',num2str(X.t*1000),'ms']);
text((fmin + (fmax-fmin)/4)/fnorm, 0.01,  ['#',num2str(X.shot),'@',num2str(X.t*1000),'ms, at dt = ',num2str(1000/mean(diff(Z.f))),'ms']);
    
% -----------------------------------------------------------------
% plot residue
% semilogy(X.f,X.dF,residue);

% for i=1:Nf
%    semilogy(Z.f(i),abs(Z.dF(i)),residue); % plot common residure
% end;

% fmin = min(X.f) + 2 * filt.fsigma;
% fmax = max(X.f) - 2 * filt.fsigma;
% rmin = 0.5 * 10^(floor(log10(min(X.dF))));
% rmax = 2;
% axis([fmin fmax rmin rmax]);

set(gca, 'YScale','log','Box','on','YTick',[0.01 0.1 1])

% set(gca, 'YScale','log','XTickLabel', '','Box','on','YTick',[0.01 0.1 1])

% ===============================================================
h1 = subplot('Position', [0.15 0.68 0.8 0.28]);
set(gca,'FontSize', fs, 'LineWidth',lw,'Box','on','TickLength',[0.02 0.02],'TickDir','in'); hold on;
set(gca,'XTickLabel','');
ylabel('|\delta B| [T Hz^{-1}]');
ylabel('|\alpha_1| [T Hz^{-1}]');
hold on;

% plot the  amplitude of the mode(s)
Nc=Z.Nc; l(1:2*Nc+1,1)=1;

% Values of OMAHA taken from stray capacitance paper 
Ncoils = 30;
A      = pi* (10.7e-3)^2;
j      = 1; % select first mode
for i=1:Nf
 
   x(l(Z.n(i,j)+Nc+1),Z.n(i,j)+Nc+1) = X.f(i);
   % y(l(Z.n(i,j)+Nc+1),Z.n(i,j)+Nc+1) = abs(Z.a(i,j)) * 1/(2*pi*Z.f(i)*Ncoils * A);
   y(l(Z.n(i,j)+Nc+1),Z.n(i,j)+Nc+1) = abs(X.a(i,j));
   l(Z.n(i,j)+Nc+1) = l(Z.n(i,j)+Nc+1) + 1;

end;

str=[];
amin = 1; amax = 1e-15;

amp_min = 1e-15;
df = X.f(2) - X.f(1);

nmap = jet(2*Nc+1);

for n=-Nc:Nc
  if l(n+Nc+1)-1>0
    nlabel = mtype(n);
    % plot(x(1:l(n+Nc+1)-1,n+Nc+1), y(1:l(n+Nc+1)-1,n+Nc+1), nlabel);
    hbar = bar1(x(1:l(n+Nc+1)-1,n+Nc+1)/fnorm, y(1:l(n+Nc+1)-1,n+Nc+1), df/fnorm, amp_min,nmap(n+1+Nc,:));
    % set(h,'UserData',['n = ',num2str(n)]);
    
    amin = min([min(y(1:l(n+Nc+1)-1,n+Nc+1)) amin]);
    amax = max([max(y(1:l(n+Nc+1)-1,n+Nc+1)) amax]);
    % if n > 11 ;
    %      str = strvcat(str,['n > 11 ']);
    % elseif n < -11 ;
    %     str = strvcat(str,['n < -11 ']);
    % else 
    % end
  end;
end;

hb = colorbar('NorthOutside');
set(hb,'XTick',[0.01 0.5 0.99]); pause(0);
set(hb,'XTickLabel',{num2str(-Nc),'n=0',num2str(Nc)})

% amin = 1; amax = 1e-15;
% for i=1:NM
    % amin = min([min(abs(Z.a(:,i))) amin]);
    % amax = max([max(abs(Z.a(:,i))) amax]);
    % amin = min([min(min(y(:,:))) amin]);
    % amax = max([max(max(y(:,:))) amax]);
% end;

mmin = 1.0 * 10^(floor(log10(amin)));
mmax = 1 *  10^(ceil(log10(amax)));
axis([fmin/fnorm fmax/fnorm mmin mmax]);
if 10*mmin ~= mmax/10
   set(gca, 'YScale','log','Box','on','YTick',[10*mmin mmax/10]);
else
   set(gca, 'YScale','log','Box','on','YTick',[mmin mmax]);
end

% set(gca, 'YScale','log', 'XTickLabel', '','Box','on','YTick',[10*mmin mmax/10])
% set(gca, 'YScale','log', 'XTickLabel', '','Box','on','YTick',[0.01 0.1 1])

% ===============================================================
h2 = subplot('Position', [0.15 0.4 0.8 0.28]);
set(gca,'FontSize', fs, 'LineWidth',lw,'Box','on','TickLength',[0.02 0.02],'TickDir','in'); hold on;
set(gca,'XTickLabel','');
ylabel('|\delta B| [T Hz^{-1}]');
ylabel('|\alpha_2| [T Hz^{-1}]');
hold on;

% plot the  amplitude of the mode(s)
Nc=Z.Nc; l(1:2*Nc+1,1)=1;

% Values of OMAHA taken from stray capacitance paper 
Ncoils = 30;
A      = pi* (10.7e-3)^2;
j      = 2; % select second mode
clear x y 
for i=1:Nf
 
   x(l(Z.n(i,j)+Nc+1),Z.n(i,j)+Nc+1) = X.f(i);
   % y(l(Z.n(i,j)+Nc+1),Z.n(i,j)+Nc+1) = abs(Z.a(i,j)) * 1/(2*pi*Z.f(i)*Ncoils * A);
   y(l(Z.n(i,j)+Nc+1),Z.n(i,j)+Nc+1) = abs(X.a(i,j));
   l(Z.n(i,j)+Nc+1) = l(Z.n(i,j)+Nc+1) + 1;

end;

str=[];
amin = 1; amax = 1e-15;

df = X.f(2) - X.f(1);

nmap = jet(2*Nc+1);

for n=-Nc:Nc
  if l(n+Nc+1)-1>0
    nlabel = mtype(n);
    % plot(x(1:l(n+Nc+1)-1,n+Nc+1), y(1:l(n+Nc+1)-1,n+Nc+1), nlabel);
    hbar = bar1(x(1:l(n+Nc+1)-1,n+Nc+1)/fnorm, y(1:l(n+Nc+1)-1,n+Nc+1), df/fnorm, amp_min,nmap(n+1+Nc,:));
    % set(h,'UserData',['n = ',num2str(n)]);
    
  end;
end;

% overlay envelope of firtst mode on second
hold on
semilogy(X.f/fnorm, abs(X.a(:,1)),'k--');

axis([fmin/fnorm fmax/fnorm mmin mmax]);
if 10*mmin ~= mmax/10
   set(gca, 'YScale','log','Box','on','YTick',[10*mmin mmax/10]);
else
   set(gca, 'YScale','log','Box','on','YTick',[mmin mmax]);
end

% set(gca, 'YScale','log', 'XTickLabel', '','Box','on','YTick',[10*mmin mmax/10])
% set(gca, 'YScale','log', 'XTickLabel', '','Box','on','YTick',[0.01 0.1 1])

linkaxes([h3 h1 h2],'x');

return